### ISSUE TITLE
Build error  The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:

### ISSUE THREAD

**Issue by codesdk** [kara/puppy-love#2]
I cloned this repo, ran npm install and then ng serve and I get the following error on my browser 👍 

Build error

The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: Typescript found the following errors:
  /Users/coder/repos/kara/puppy-love/tmp/broccoli_type_script_compiler-input_base_path-Afc2X3rD.tmp/0/src/main.ts (3, 30): Cannot find module '@angular/http'.
    at BroccoliTypeScriptCompiler._doIncrementalBuild (/Users/coder/repos/kara/puppy-love/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:115:19)
    at BroccoliTypeScriptCompiler.build (/Users/coder/repos/kara/puppy-love/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:43:10)
    at /Users/coder/repos/kara/puppy-love/node_modules/broccoli-caching-writer/index.js:152:21
    at lib$rsvp$$internal$$tryCatch (/Users/coder/repos/kara/puppy-love/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/coder/repos/kara/puppy-love/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/Users/coder/repos/kara/puppy-love/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/Users/coder/repos/kara/puppy-love/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at: 
    at BroccoliTypeScriptCompiler.Plugin (/Users/coder/repos/kara/puppy-love/node_modules/broccoli-plugin/index.js:10:31)
    at BroccoliTypeScriptCompiler.CachingWriter [as constructor] (/Users/coder/repos/kara/puppy-love/node_modules/broccoli-caching-writer/index.js:21:10)
    at BroccoliTypeScriptCompiler (/Users/coder/repos/kara/puppy-love/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:27:5)
    at Angular2App._getTsTree (/Users/coder/repos/kara/puppy-love/node_modules/angular-cli/lib/broccoli/angular2-app.js:280:18)
    at Angular2App._buildTree (/Users/coder/repos/kara/puppy-love/node_modules/angular-cli/lib/broccoli/angular2-app.js:101:23)
    at new Angular2App (/Users/coder/repos/kara/puppy-love/node_modules/angular-cli/lib/broccoli/angular2-app.js:42:23)
    at module.exports (/Users/coder/repos/kara/puppy-love/angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/Users/coder/repos/kara/puppy-love/node_modules/ember-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/Users/coder/repos/kara/puppy-love/node_modules/ember-cli/lib/models/builder.js:89:10)
    at new Class (/Users/coder/repos/kara/puppy-love/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/Users/coder/repos/kara/puppy-love/node_modules/ember-cli/lib/tasks/serve.js:15:19)
    at /Users/coder/repos/kara/puppy-love/node_modules/ember-cli/lib/commands/serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (/Users/coder/repos/kara/puppy-love/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/coder/repos/kara/puppy-love/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /Users/coder/repos/kara/puppy-love/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/Users/coder/repos/kara/puppy-love/node_modules/rsvp/dist/rsvp.js:1198:9)

The console log is as follows : 

==> ng serve
(node:27365) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
Could not start watchman; falling back to NodeWatcher for file system events.
Visit http://ember-cli.com/user-guide/#watchman for more info.
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
The Broccoli Plugin: [BroccoliTypeScriptCompiler] failed with:
Error: Typescript found the following errors:
  /Users/coder/repos/kara/puppy-love/tmp/broccoli_type_script_compiler-input_base_path-PCRTU4nW.tmp/0/src/main.ts (3, 30): Cannot find module '@angular/http'.
    at BroccoliTypeScriptCompiler._doIncrementalBuild (/Users/coder/repos/kara/puppy-love/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:115:19)
    at BroccoliTypeScriptCompiler.build (/Users/coder/repos/kara/puppy-love/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:43:10)
    at /Users/coder/repos/kara/puppy-love/node_modules/broccoli-caching-writer/index.js:152:21
    at lib$rsvp$$internal$$tryCatch (/Users/coder/repos/kara/puppy-love/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/coder/repos/kara/puppy-love/node_modules/rsvp/dist/rsvp.js:1048:17)
    at lib$rsvp$$internal$$publish (/Users/coder/repos/kara/puppy-love/node_modules/rsvp/dist/rsvp.js:1019:11)
    at lib$rsvp$asap$$flush (/Users/coder/repos/kara/puppy-love/node_modules/rsvp/dist/rsvp.js:1198:9)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

The broccoli plugin was instantiated at: 
    at BroccoliTypeScriptCompiler.Plugin (/Users/coder/repos/kara/puppy-love/node_modules/broccoli-plugin/index.js:10:31)
    at BroccoliTypeScriptCompiler.CachingWriter [as constructor] (/Users/coder/repos/kara/puppy-love/node_modules/broccoli-caching-writer/index.js:21:10)
    at BroccoliTypeScriptCompiler (/Users/coder/repos/kara/puppy-love/node_modules/angular-cli/lib/broccoli/broccoli-typescript.js:27:5)
    at Angular2App._getTsTree (/Users/coder/repos/kara/puppy-love/node_modules/angular-cli/lib/broccoli/angular2-app.js:280:18)
    at Angular2App._buildTree (/Users/coder/repos/kara/puppy-love/node_modules/angular-cli/lib/broccoli/angular2-app.js:101:23)
    at new Angular2App (/Users/coder/repos/kara/puppy-love/node_modules/angular-cli/lib/broccoli/angular2-app.js:42:23)
    at module.exports (/Users/coder/repos/kara/puppy-love/angular-cli-build.js:6:10)
    at Class.module.exports.Task.extend.setupBroccoliBuilder (/Users/coder/repos/kara/puppy-love/node_modules/angular-cli/lib/models/builder.js:55:19)
    at Class.module.exports.Task.extend.init (/Users/coder/repos/kara/puppy-love/node_modules/angular-cli/lib/models/builder.js:89:10)
    at new Class (/Users/coder/repos/kara/puppy-love/node_modules/core-object/core-object.js:18:12)
    at Class.module.exports.Task.extend.run (/Users/coder/repos/kara/puppy-love/node_modules/angular-cli/lib/tasks/serve.js:15:19)
    at /Users/coder/repos/kara/puppy-love/node_modules/angular-cli/lib/commands/serve.js:64:24
    at lib$rsvp$$internal$$tryCatch (/Users/coder/repos/kara/puppy-love/node_modules/rsvp/dist/rsvp.js:1036:16)
    at lib$rsvp$$internal$$invokeCallback (/Users/coder/repos/kara/puppy-love/node_modules/rsvp/dist/rsvp.js:1048:17)
    at /Users/coder/repos/kara/puppy-love/node_modules/rsvp/dist/rsvp.js:331:11
    at lib$rsvp$asap$$flush (/Users/coder/repos/kara/puppy-love/node_modules/rsvp/dist/rsvp.js:1198:9)

Am I missing a dependency? Could you please add some documentation for how to build and run?

**Comment by maxime1992** [comment]
I do have the same error, I thought I had to run
```
npm install
typings install
ng serve
```

But I have this broccoli error.

Great talk at ng-conf BTW :)

**Comment by dkrystall** [comment]
@codesdk @maxime1992 it looks like you need to install the @angular/http component,
go into the terminal and type:  npm i @angular/http

That's what was missing from mine also when I cloned it, have it working fine now

**Comment by codesdk** [comment]
Hi @maxime1992 and @dkrystall 

I did 
npm install

typings install

npm install @angular/http 

But I got this error 

==> npm install @angular/http
puppy-love@0.0.0 /Users/coder/repos/codesdk/githubrepos/puppy-love
├── UNMET PEER DEPENDENCY @angular/core@2.0.0-rc.0
├── UNMET PEER DEPENDENCY @angular/http@2.0.0-rc.1 extraneous
└── UNMET PEER DEPENDENCY angular2@^2.0.0-beta.8

npm WARN @angular/http@2.0.0-rc.1 requires a peer of @angular/core@2.0.0-rc.1 but none was installed.
npm WARN @angular2-material/card@2.0.0-alpha.4 requires a peer of angular2@^2.0.0-beta.8 but none was installed.
npm WARN @angular2-material/checkbox@2.0.0-alpha.4 requires a peer of angular2@^2.0.0-beta.8 but none was installed.
npm WARN @angular2-material/icon@2.0.0-alpha.4 requires a peer of @angular/http@2.0.0-rc.0 but none was installed.
npm ERR! code 1

Ran 
ng serve

And it runs fine on the browser so I guess I should close this issue?
Unless you know what is causing the npm ERR right at the end?

Also, should I do 

npm install @angular/http --save ?

**Comment by codesdk** [comment]
Created pull request 

https://github.com/kara/puppy-love/pull/3

**Comment by kara** [comment]
Thanks for the issue!  I'm actually trying to keep this code true to what I actually demo-ed at the conference, so I'm not accepting pull requests. But I will definitely add something to the README about the missing dependency to avoid confusion. Thanks for letting me know!
